services:
  app:
    build: .
    container_name: vsbore_bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/vsbore.db
